#!/bin/sh
## Functions

# Decompress any archive TODO use only 7z
extract () {
 if [ -f "$1" ] ; then
   case "$1" in
	*.tar.bz2)	tar xvjf $1	;;
	*.tar.gz)	tar xvzf $1	;;
	*.tar.xz)	tar xvJf $1	;;
	*.bz2)		bunzip2 $1	;;
	*.rar)		unrar x $1	;;
	*.gz)		gunzip $1	;;
	*.tar)		tar xvf $1	;;
	*.tbz2)		tar xvjf $1	;;
	*.tgz)		tar xvzf $1	;;
	*.zip)		unzip $1	;;
	*.Z)		uncompress $1	;;
	*.7z)		7z x $1		;;
	*.xz)		unxz $1		;;
	*.exe)		cabextract $1	;;
	*)	echo "\`$1': unrecognized file compression"	;;
    esac
  else
    echo "\`$1\' is not a valid file"
  fi
}

# auto-ls on cd
cd () {
 builtin cd $@ && ls
}

# Creates an archive from given directory
mktar() { tar cvf  "${1%%/}.tar"     "${1%%/}/"; }

# Create a new directory and enter it
mkcd () { 
 mkdir $1 && cd $1
}

# Move file to a directory and enter it
mvcd () { 
 mv $1 $2 && cd $2 
}

# Define stuff
google () {
 url=$(echo http://google.com/search?q=$(echo "$@" | sed s/\ /+/g))
 if [[ "$DISPLAY" = "" ]]; then
 	$BROWSER "$url"
 else
	firefox "$url"
 fi
}

# Find and execute a command in history
hist () {
 #history | sed s/.*\ \ // | grep $@
 history | grep --color=auto $1

 echo "Execute  command #?"
 read number
 
 `history | grep $number | tr -s ' ' | cut -d ' ' -f 3-`
}

# color diffs for CVS
cvsdiff () {
  if [ "$1" != "" ]; then
    cvs diff $@ | colordiff;
  else
    cvs diff | colordiff;
  fi
}

# clyde - no more manual sudo
clyde() {
	case $1 in
		(-Ss | -Si | -Q* | -T | -G)
			/usr/bin/clyde "$@" ;;
		(-S* | -R* | -U | *)
			/usr/bin/sudo /usr/bin/clyde "$@" ;;
	esac
}

