#!/bin/sh

#xwininfo hack since xdotool --only-visible is broken
wid=$(xdotool search --name urxvtq)
if [ -z "$wid" ]; then
  #~/.config/urxvtc -name urxvtq -geometry 240x28 -bl
  ~/Scripts/urxvtc -name urxvtq -geometry 180x60 -bl
    wid=$(xdotool search --name urxvtq)
    xdotool windowfocus $wid
else
  if [ -z "$(xwininfo -id $wid | grep 'IsViewable')" ]; then
    xdotool windowmap $wid
    xdotool windowfocus $wid
  else
    xdotool windowunmap $wid
  fi
fi
