#!/bin/sh

BG='#101010'     # dzen background
FG='#ffffff'     # dzen foreground
W=45         # width of the dzen bar
GW=40         #  width of the volume gauge
GH=7          # height of the gauge
GFG='#395573' # color of the gauge
GBG='#333'    # color of gauge background
VOL_GW=10         #  width of the volume gauge
VOL_GH=20          # height of the gauge
VOL_GFG='#395573' # color of the gauge
VOL_GBG='#333'    # color of gauge background
BAT_GW=50      # width of the gauge
BAT_GH=7       # height of the gauge
BAT_GFG='#80CC83'  # color of the gauge
BAT_GBG='#333'  # color of gauge background
X=0         # x position
Y=0         # y position
 
# Font to use
#FN='-xos4-terminus-*-*-*-*-10-*-*-*-*-*-*-*'
#FN='-*-terminal-*-*-*-*-10-*-*-*-*-*-*-*'
#FN='-*-terminus-*-r-normal-*-*-120-*-*-*-*-iso8859-*'
FN="-windows-montecarlo-medium-r-normal--11-110-72-72-c-60-microsoft-cp1252"


SLEEP=1         # time interval in seconds
ICONPATH='/home/ricardo/Scripts/dzen/xbm'

 
# Workspace settings {{{
	WS_ACTIVE="^i(${ICONPATH}/has_win.xbm)"
	WS_INACTIVE="^i(${ICONPATH}/has_win_nv.xbm)"
	HOST=ricardoArch
	LAST_WS=main
# }}}
# Tasks settings {{{
	TASK_ACTIVE_ID=`xprop -root _NET_ACTIVE_WINDOW | awk '{print $5}' | cut -b 3-`;
	#TASK_ACTIVE_NAME=`wmctrl -l | awk "/$TASK_ACTIVE_ID/"'{for (i=4; i<=NF; i++) print $i;}' | cut -b-70`;
	TASK_FG='#afff2f'
# }}}
# Mail settings {{{
	MAIL_CAPTION="^i(${ICONPATH}8x8/mail.xbm)"
	MAILFILE='/home/ricardo/Mail/GMAIL/Inbox';
#}}}
# Battery settings {{{
STATEFILE='/proc/acpi/battery/BAT1/state' # battery's state file
INFOFILE='/proc/acpi/battery/BAT1/info'   # battery's info file
 
#LOWBAT=15        # percentage of battery life marked as low
LOWCOL='#ff4747' # color when battery is low
MIDCOL='khaki' # color when battery is low
HIGHCOL='#80CC83' # color when battery is low

#BAT_CAPTION="^i(${ICONPATH}/power-bat2.xbm)"
BAT_FULL="^i(${ICONPATH}8x8/bat_full_02.xbm)"
BAT_MID="^i(${ICONPATH}8x8/bat_low_02.xbm)"
BAT_LOW="^i(${ICONPATH}8x8/bat_empty_02.xbm)"
AC_CAPTION="^i(${ICONPATH}8x8/ac_01.xbm)"
 
BAT_TOTAL=4800;
#RCAP=`cat $STATEFILE|grep remaining|cut -d " " -f 8`;
#}}}
# Volume settings {{{
# Captions of the gauge
VOL_CAPTION="^i(${ICONPATH}8x8/spkr_01.xbm)"
VOL_CAPTION_MUTE="^i(${ICONPATH}8x8/spkr_02.xbm)"
#VOL_CAPTION="^i(${ICONPATH}/vol-hi.xbm)"
#VOL_CAPTION_MUTE="^i(${ICONPATH}/vol-mute.xbm)"
	 
# command to increase the volume
CI="amixer -c0 sset PCM 2dB+ >/dev/null"
#CI="aumix -v +5"
# command to decrease the volume
CD="amixer -c0 sset PCM 2dB- >/dev/null"
#CD="aumix -v -5
 
# command to pipe into gdbar to display the gauge
# should print out 2 space-seperated values, the first is the current
# volume, the second the maximum volume
#MAX=`amixer -c0 get PCM | awk '/^  Limits/ { print $5 }'`
#MAX=255
#CV="amixer -c0 get PCM | awk '/^  Front Left/ { print \$4 * 100 / $MAX}'"
CV="amixer -c0 get PCM | awk '/^  Front Left/ { print \$5 }' | tr -d '[]'" ;
#CV="aumix -q | line | cut -d \" \" -f 3"

# }}}
# MPC settings {{{
MPC_CAPTION="^i(${ICONPATH}8x8/phones.xbm)"
MPC_PLAY_CAPTION="^i(${ICONPATH}8x8/play.xbm)"
MPC_PAUSE_CAPTION="^i(${ICONPATH}8x8/pause.xbm)"
MPC_STOP_CAPTION="^i(${ICONPATH}8x8/stop.xbm)"
#MPC_SONG="/usr/bin/mpc current | tr '\n' ' ' "
MPC_SONG="/usr/bin/mpc current | cut -b-60 | tr '\n' ' ' "
#MPC_FG='#7744AA'
MPC_FG='#B0AA83'
# }}}
# Load settings {{{
CPU_CAPTION="^i(${ICONPATH}8x8/cpu.xbm)"
#}}}
# Net settings {{{
INTERFACE=wlan0
	# Here we remember the previous rx/tx counts
	RXB=`cat /sys/class/net/${INTERFACE}/statistics/rx_bytes`
	TXB=`cat /sys/class/net/${INTERFACE}/statistics/tx_bytes`
#}}}
# ESSID settings {{{
WIFI_CAPTION="^i(${ICONPATH}8x8/wifi_01.xbm)"
#}}}
# Pacman settings {{{
PACMAN_CAPTION="^i(${ICONPATH}8x8/pacman.xbm)";
PACMAN_FILE='~/Scripts/pacman_updates';
# }}}
# Date settings {{{
DARKGRAY='#555555'
#}}}

while true; do
#Left Format
 echo -n "^p(_LEFT)";
 echo -n "^p(-5X)";
#Arch Icon {{{
 echo -n "^fg(lightblue3)";
 #echo -n "^i(${ICONPATH}8x8/arch.xbm)";
 echo -n "^i(${ICONPATH}8x8/arch_10x10.xbm)";
 echo -n "^p(2X)";
#}}}
#Workspace info {{{
WS_ACTIVE="^i(${ICONPATH}/has_win.xbm)"
WS_INACTIVE="^i(${ICONPATH}/has_win_nv.xbm)"
WS=` wmctrl -d | awk '/\*/ {print $10}' `

 NUM_TASK=0;
 i=0;
 for ws in {main,web,code,misc}; do
	 echo -n "^ca(1,wmctrl -s $i)";
	 NUM_WIN=`wmctrl -l | awk "/ $i $HOST/"'{ i += 1 } END { print i }' `;
	 #echo -n "$NUM_WIN";
	 if [[ $WS == $ws ]]; then
		 echo -n "^fg(gray)$ws";
		 if [[ $LAST_WS != $ws ]]; then
			 feh --bg-scale ~/Walls/$ws;
		 fi
		 LAST_WS=$ws;
		 if [[ $NUM_WIN -gt 0 ]]; then
			 echo -n "$WS_ACTIVE";
			 NUM_TASK=$NUM_WIN;
		 else
			 echo -n " ";
			 NUM_TASK=0;
		 fi
	 else
		 echo -n "^fg($DARKGRAY)$ws";
		 #echo -n "^fg($MPC_FG)^bg(black)$ws";
		 if [[ $NUM_WIN -gt 0 ]]; then
			 echo -n "^fg(gray)$WS_INACTIVE";
		 else
			 echo -n " ";
		 fi
	 fi
	 echo -n "^ca()^fg()^bg()";
	 i=`expr $i + 1` #shell script i++
 done
# }}}
#Layout info {{{
	#TODO -> get a better tiling manager
	#echo -n " ^i(${ICONPATH}/mtall.xbm) ^fg($TASK_FG)$NUM_TASK^fg()";
 
#}}}
#ICON info {{{
	#echo -n " ^fg(green3)^i(${ICONPATH}8x8/info_01.xbm)";
	#echo -n "^p(2X)$NUM_TASK^fg()";
	#echo -n " ^fg($TASK_FG)$NUM_TASK^fg()";
	#echo -n " ^bg(black)^fg(lightblue3)";
	#echo -n " ^fg(black)^bg(#DDDD83)";
	#echo -n " ^fg(black)^bg($TASK_FG)";
#}}}
#Tasks info {{{
	#TASK_ACTIVE_ID=`xprop -root _NET_ACTIVE_WINDOW | awk '{print $5}' | cut -b 3-`;
	#TASK_ACTIVE_NAME=`wmctrl -l | awk "/$TASK_ACTIVE_ID/"'{for (i=4; i<=NF; i++) print $i;}' | cut -b-70`;
	#echo -n " { $TASK_ACTIVE_ID }";
	#if [[ $NUM_TASK != 0 ]]; then
	#if [[ $TASK_ACTIVE_ID != 0 && $NUM_TASK != 0 ]]; then
		#[[ $NUM_TASK -gt 1 ]] && echo -n "^p(2X)$NUM_TASK^fg()";

		#echo -n " ^bg(#444444)^fg($TASK_FG)";
		#echo -n "^bg(#444444)^fg(lightblue2)^p(2X)";
		#echo -n `wmctrl -l | awk "/$TASK_ACTIVE_ID/"'{for (i=4; i<=NF; i++) \
			#print $i, $++i, $++i, $++i, $++i, $++i, $++i, $++i, $++i, $++i, \
			#$++i, $++i, $++i, $++i, $++i, $++i, $++i;}' \
			#| cut -b-60`;
		#echo -n "^bg()";
		#echo -n "$TASK_ACTIVE_NAME"; 
	#fi
#}}}
#Center Format
 echo -n "^p(_CENTER)";
 echo -n "^p(-400X)";
#MPC info {{{
	MPC=$(/usr/bin/mpc);
	#echo -n "$MPC";
	MPC_STATUS=$(echo "$MPC" | awk '/#/ {print $1}' );
	#echo -n $MPC_STATUS;

	echo -n "^p(10X)";
	echo -n "^ca(1,sonata -t)^ca(2,mpc -q toggle)^ca(4,mpc -q next)^ca(5,mpc -q prev)^fg($DARKGRAY)";
	case $(echo $MPC_STATUS) in
		\[playing\])
			#MPC_TIME_LEFT=`/usr/bin/mpc status | awk -F: '/#/ {print $3 - $2}'`;
			MPC_LENGTH=$(echo "$MPC"| awk '/#/ {print $3}');
			#MPC_LENGTH=`/usr/bin/mpc status | awk '/#/ {print $3}'`
			echo -n "$MPC_CAPTION^p(3X)";
			echo -n "^ca(1,mpc -q random)";
			echo -n "[";
			STAT=$(echo "$MPC"| awk '/random:/ {print $5}');
			echo -n "$STAT";
			echo -n "]";
			echo -n "^ca()";
			echo -n $MPC_PLAY_CAPTION;
			echo -n "($MPC_LENGTH) ";
			echo -n "^fg($MPC_FG)";
			#echo -n "^fg($TASK_FG)";
			MPC_SONGNAME=$(eval $MPC_SONG);
		;;
		\[paused\])
			MPC_LENGTH=$(echo "$MPC"| awk '/#/ {print $3}');
			echo -n "$MPC_CAPTION^p(3X)";
			echo -n $MPC_PAUSE_CAPTION;
			echo -n "^fg($DARKGRAY)";
			echo -n "($MPC_LENGTH) ";
			MPC_SONGNAME=$(eval $MPC_SONG);
		;;
		*)
			echo -n "$MPC_CAPTION^p(3X)";
			echo -n "$MPC_STOP_CAPTION^p(3x)";
		;;
	esac
	echo -n "$MPC_SONGNAME";
	echo -n "^ca()^ca()^ca()^ca()^fg()";
#}}}
#Right Format
 echo -n "^p(_RIGHT)";
 echo -n "^p(-630)";
#Load info {{{
 echo -n "^fg($DARKGRAY)";
 echo -n "$CPU_CAPTION^p(3X)";
 echo -n "^fg(gray)";
 perl ~/Scripts/dzen/load.pl;
 #echo -n `uptime | awk '// {print $(NF-2), $(NF-1), $NF}' `;
#}}}
#ESSID info {{{
 echo -n "^p(_RIGHT)";
 echo -n "^p(-510)";
 echo -n "^fg($DARKGRAY)";
 ESSID=`iwgetid -r`;
 echo -n "$WIFI_CAPTION ";
 if [[ -n $ESSID ]]; then
	 echo -n "^fg($HIGHCOL)$ESSID";
	 #Net info {{{
	 echo -n "^p(_RIGHT)";
	 echo -n "^p(-400)";
	 # get new rx/tx counts
	 RXBN=`cat /sys/class/net/${INTERFACE}/statistics/rx_bytes`
	 TXBN=`cat /sys/class/net/${INTERFACE}/statistics/tx_bytes`

	 # calculate the rates
	 # format the values to 4 digit fields
	 RXDIFF="$(expr $RXBN - $RXB)"
	 TXDIFF="$(expr $TXBN - $TXB)"
	 RXR="$(echo $(expr $RXDIFF / 1024 / $SLEEP ))"
	 TXR="$(echo $(expr $TXDIFF / 1024 / $SLEEP ))"
	 #RXR="$(printf "%4d" $(echo $(expr $RXDIFF / 1024)) )"
	 #TXR="$(printf "%4d" $(echo $(expr $TXDIFF / 1024)) )"

	 echo -n "^fg($DARKGRAY)^i(${ICONPATH}8x8/net_down_01.xbm)";
	 if [[ ${RXR} -gt 0 ]]; then
		 echo -n "^p(2X)^fg(#80AA83)${RXR} kB/s";
	 else
		 echo -n "^p(2X)${RXR} kB/s";
	 fi

	 echo -n "^p(_RIGHT)^p(-330X)";
	 echo -n "^fg($DARKGRAY)^i(${ICONPATH}8x8/net_up_01.xbm)"
	 if [[ ${TXR} -gt 0 ]]; then
		 echo -n "^p(2X)^fg(orange3)${TXR} kB/s";
	 else
		 echo -n "^p(2X)${TXR} kB/s";
	 fi

	 # reset old rates
	 RXB=$RXBN; TXB=$TXBN
	 #}}}
 else
	 echo -n "^fg($LOWCOL)Disconnected";
 fi
#}}}
#Mail info {{{
	echo -n "^p(_RIGHT)^p(-260)";
	NEW_MAIL=`awk '/Message-I[[:alpha:]]:/ { i+=1 } END {print i}' $MAILFILE`;
	if [[ -n $NEW_MAIL ]]; then
		echo -n "^fg($DARKGRAY)";
		echo -n "$MAIL_CAPTION^p(3X)";
		echo -n "^fg($LOWCOL)$NEW_MAIL";
	else
		echo -n "^fg($DARKGRAY)";
		echo -n "$MAIL_CAPTION^p(3X)";
		echo -n "0";
		#echo -n "^fg($HIGHCOL)0^fg()";
	fi
#}}}
#Pacman info {{{
	echo -n "^p(_RIGHT)^p(-230X)";
	echo -n "^fg($DARKGRAY)";
	UP=`cat ~/Scripts/pacman_updates`;
	if [[ $UP -gt 0 ]]; then 
		#echo -n "^ca(1,notify-send `pacman -Qu`)";
		echo -n "$PACMAN_CAPTION^p(3X)";
		echo -n "^fg(yellow3)";
		echo -n $UP;
		#echo -n "^ca()";
	else
		echo -n "$PACMAN_CAPTION^p(3X)";
		echo -n $UP;
	fi
#}}}
#Battery/ac info {{{
	echo -n "^p(_RIGHT)^p(-210X)";
	echo -n "^fg($DARKGRAY)";
	RCAP=`awk '/remaining/ {print $3 }' $STATEFILE`;
	if [[ -n $RCAP ]]; then
		# calculate remaining power
		#RPERCT=`expr $RCAP \* 100`;
		#RPERC=`expr $RPERCT / $BAT_FULL`;
		RPERC=`expr $RCAP \* 100 / $BAT_TOTAL`;
		 
		if [ $RPERC -le 15 ]; then BAT_GFG=$LOWCOL; BAT_CAPTION=$BAT_LOW;
		elif [ $RPERC -le 50 ]; then BAT_GFG=$MIDCOL; BAT_CAPTION=$BAT_MID;
		else BAT_GFG=$HIGHCOL; BAT_CAPTION=$BAT_FULL;
		fi
		echo -n "^p(3X) $BAT_CAPTION^p(3X)";
		#echo -n `echo -n "$RPERC" | gdbar -s o -h $BAT_GH -w $BAT_GW -fg $BAT_GFG -bg $BAT_GBG;`
		echo -n "^fg($BAT_GFG)$RPERC%^fg()";
	else
		echo -n "^p(3X) $AC_CAPTION ^fg($DARKGRAY)On^fg()";
		#echo -n "^p(3X) $AC_CAPTION ^fg($HIGHCOL)On^fg()";
	fi 
#}}}
#Volume info {{{
	echo -n "^p(_RIGHT)^p(-160X)";
	echo -n "^fg($DARKGRAY)";
	echo -n "^ca(1,amixer -q set Master toggle)";
	VOL=$(eval "$CV");
	MUTE=`amixer -c0 get Master | awk '/\[off\]/ {print $6}'`;
	if [[ $MUTE == "[off]" ]]; then 
		echo -n $VOL_CAPTION_MUTE;
		echo -n "^p(3X)";
		echo -n "^fg($LOWCOL)Muted^ca()";
	else
		echo -n $VOL_CAPTION;
		echo -n "^p(3X)";
		if [[ $VOL != $OLD_VOL ]]; then
			echo -n "^fg(lightblue3)";
		fi
		echo -n "$VOL^ca()";
	fi
	OLD_VOL=$VOL;
	#echo -n $NUM | gdbar -nonl -ss 0 -s v -sw 8 -sh 1 -h $VOL_GH -w $VOL_GW -fg $VOL_GFG -bg $VOL_GBG;
#}}}
#Date {{{
	echo -n "^p(_RIGHT)";
	echo -n "^p(-97X)";
	echo -n "^fg($DARKGRAY)";
	echo -n "^i(${ICONPATH}8x8/clock.xbm) "
	echo -n "^p(3X)";
	echo -n `date +"%d %b"`;
	echo -n " ^fg(gray)"
	echo `date +"%H:%M"`;
	#echo -n "^p(-55X)";
	#echo `date +"%H:%M" `;
#}}}
sleep $SLEEP;

done | dzen2 -ta left -y $Y -x $X -fg $FG -bg $BG -e "entertitle=uncollapse,unhide;button2=exit;button3=hide;button4=exec:$CI;button5=exec:$CD" -fn $FN
